# -*- coding: utf-8 -*-
"""18WH1A05A8_Program1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ppVE9SR3SmDYXU8yifKgU9OlxM1IXdX2
"""



probStudAbsentAndFriday = 0.03
probFriday =0.2
bayesResult = (probStudAbsentAndFriday/probFriday)
print (bayesResult *100)