# -*- coding: utf-8 -*-
"""18WH1A0590_Program01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14drrdtDtgadUAyM7SVHwXgYNnTrzLRaU
"""

probStudAbsentAndFriday = 0.03
probFriday =0.2
bayesResult = (probStudAbsentAndFriday/probFriday)
print (bayesResult *100)