# -*- coding: utf-8 -*-
"""Program1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1USPsiMtCocOxnbQ6Wy0JdKzw2Kjt9MC8
"""

# Probability of Student being absent on Friday
prodofAbsentndFri= 0.03

# Probability of Friday
probofFriday = 0.2

result = prodofAbsentndFri/probofFriday

print(result*100)