# -*- coding: utf-8 -*-
"""18WH1A05A9_Program 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-QUeqrv8jHUj26Go1dZ7NwkqPKk7Dgl
"""

probStudAbsentAndFriday = 0.03
probFriday =0.2
bayesResult = (probStudAbsentAndFriday/probFriday)
print (bayesResult *100)